### PR TITLE
Fixed types for the `Image` component

### LINKED ISSUE #940: <Image> does not support the `style` prop in TypeScript
There are examples in the [Thumbprint docs for the Image component](https://thumbprint.thumbtack.com/components/image/react/) that use the `style` prop to set the image width.

Image__React____Thumbprint

Currently, a TS error occurs if you try to add such a `style` prop to the `<Image>` component:

Fullscreen_7_10_23__1_27_PM

### PR DESCRIPTION
**Pull request by danoc**
We spread `props` on the `picture` element, but our types don't reflect that.

Fixes #940.

### CODE REVIEW

**Comment by danoc** [comment]
@lavelle, @dcapo — PTAL

File: packages/thumbprint-react/components/Image/index.tsx [hunk 1]
```diff
@@ -22,7 +22,8 @@ type ImageSource = {
     srcSet: string;
 };
 
-export interface ImageProps {
+export interface ImageProps
+    extends React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> {
```
Comment (lavelle) [inline packages/thumbprint-react/components/Image/index.tsx:26]: Should this be HTMLPictureElement, instead of the generic HTMLElement?

Comment (danoc) [reply packages/thumbprint-react/components/Image/index.tsx:26]: I don't think so. When I hover on `<picture`, I get this type definition:
image

Comment (lavelle) [reply packages/thumbprint-react/components/Image/index.tsx:26]: Ah interesting, yeah I think that's technically a bug in the DOM typings, though in practice it doesn't matter because <picture> doesn't have any custom attributes, so it's equivalent to the generic interface. We can stick with this for consistency with the DOM typings

**Review by lavelle — APPROVED** [review]
